# We have a conf and classes directory, add to BBPATH

BBPATH .= ":${LAYERDIR}"

BBFILE_COLLECTIONS += "rz-web-streamer"
BBFILE_PATTERN_rz-web-streamer := "^${LAYERDIR}/"

BBFILE_PRIORITY_rz-web-streamer = "30"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*.bb \
    ${LAYERDIR}/recipes-*/*.bbappend \
    ${LAYERDIR}/recipes-*/*/*.bbappend"
